%YAML 1.2
---
version: '0.2'

package-group: org.springframework.boot
package-name: spring-boot-starter-web
package-version: 3.5.4

repository-path: tests/repo/
repository-mode: local
output-path: output.svg
ascii-format: tree
max-depth: 3